### ISSUE TITLE
Bad Input

### ISSUE THREAD

**Issue by Vaish1405** [smf-steve/integers-conversion-encoding#1]
How should we handle the situation when a user puts in a bogus value?

-  do a poppup?
-  make the field turn red?
- set all the fields to invalid?

**Comment by l-olmos** [comment]
I think we should either make the field turn red or set all the fields to invalid. However, I think just setting the field red may not be enough b/c the user may not understand, so we can have a little icon like this: 
<img width="170" alt="image" src="https://user-images.githubusercontent.com/98084017/201811745-293a6e00-53cb-4161-b6c5-2edbebb2dc78.png">

OR
<img width="147" alt="image" src="https://user-images.githubusercontent.com/98084017/201811827-f9e74d27-76d7-4ada-883d-6d5c1e8ec44d.png">
Just changing "zip" to "number". 

Or we can just set all the fields to invalid. Doing both doesn't seem right to me.
